### ISSUE TITLE
Support for Type Checking

### ISSUE THREAD

**Issue by tiagoefmoraes** [tkqubo/codeclimate-tslint#11]
Some tslint rules require type checking. I didn't find how to configure codeclimate-tslint to enabled it.

Some information from tslint docs:

```typescript
const program = Linter.createProgram("tsconfig.json", "projectDir/");
const files = Linter.getFileNames(program);
const results = files.map(file => {
    const fileContents = program.getSourceFile(file).getFullText();
    const linter = new Linter(file, fileContents, options, program);
    return linter.lint();
});
```
see: https://github.com/palantir/tslint#type-checking

**Comment by phgroe** [comment]
With current versions of TSlint, type checking can only be enabled via command line parameter and not through its config file itself. Additionally, as soon as you enable type checking, it wants another parameter called `--project` that will point to the `tsconfig.json` file. The latter shouldn't be necessary at all, if the _default_ project file in the _default_ location is present.

I don't understand that particular design choice, because it makes integration of TSlint a lot more complicated than it would have to be, for example if all options and switches were available through `tslint.json` (and not only for Codeclimate but also in editors that support TSlint). Or maybe these options _are_ available in the config file but the documentation doesn't mention it.

So, I guess this engine has to explicitely activate it by forwarding those parameters to TSlint and the "need to do so" has to be expressed somehow in `.codeclimate.yml`
